name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Build Site
        run: echo "Building site..."
      - name: Deploy
        uses: actions/deploy-pages@v1

permissions:
  contents: write
  pages: write

